### PR TITLE
feat: adding support for webhook notifications

### PR DESCRIPTION
**Pull request by cbhoffman**
This will enable the use of webhook notifications within alerts using the recent SDK release.

Currently, you will receive an error if you set up alert rule notifications that use a custom webhook integration (for example, a Microsoft Teams integration data source) within Terraform.

Any feedback would be appreciated, thank you!

@joaomper-TE @shahid-te @pedro-te @phpinhei-te

### CODE REVIEW

**Review by shahid-te — APPROVED** [review]
Thanks for contributing 😄

**Comment by cbhoffman** [comment]
> @cbhoffman thanks for contributing. FYI the build is failing because of this:
> 
> https://github.com/thousandeyes/terraform-provider-thousandeyes?tab=readme-ov-file#maintainers
> 
> ```
> The docs/ folder should not be changed manually. Instead, if there are changes to the examples, inputs/outputs of any data_source or resource, you need to run go generate locally and commit the resulting changes to the .md files.
> ```

Ok thanks for letting me know, sorry about that! I'll fix this morning.

**Comment by cbhoffman** [comment]
When possible, can someone approve the workflow please. @joaomper-TE @shahid-te

**Review by shahid-te — APPROVED** [review]

**Review by joaomper-TE — APPROVED** [review]

**Comment by joaomper-TE** [comment]
@cbhoffman release under v2.0.8 https://github.com/thousandeyes/terraform-provider-thousandeyes/releases/tag/v2.0.8

**Pull request merged**
